drop table if exists blogs;

create table blogs (
	BlogID int unsigned not null auto_increment primary key,
	BlogTitle varchar(100),
	BlogImg varchar(100),
	BlogEntry varchar(8192)
);


insert into blogs values


	(NULL,"PHP is an elephant's best friend","php.png","Programmer humor Programming Raising the taxes of graduate students by as much as 300% will be a disaster for the usa Orangered alert the senate is about to vote on whether to restore net neutrality for the first time since 1908, the chicago cubs are world champions. Megathread intelligence report claims russia has compromising information on trump 
<br><br>
Megathread fbi director comey fired Xbox is now going to allow customers to self-refund any game purchased within 14 days with under 2 hours of playtime. please, let's put the pressure on sony to implement something like this as well. We're nasa mars scientists. ask us anything about today's news announcement of liquid water on mars. Megathread paul manafort ordered to jail after witness-tampering charges Megathread donald trump jr. releases correspondence from russian lawyer Megathread sean spicer resigns from white house press secretary position R/the donald is imploding, following trump's pro-gun control comments, users upset and expressing distaste with trump, mods are banning countless longtime posters / anyone disagreeing with trump. it's thoroughly good - and happening right now. Ysk the $35 that scientific journals charge you to read a paper goes 100% to the publisher and 0% to the authors. if you email a researcher and ask for their paper, they are allowed to send them to you for free and will be genuinely delighted to do so. 
<br><br>
Megathread michael flynn resigns as national security advisor Megathread trump dismisses anthony scaramucci as white house communications director Megathread trump's former lawyer michael cohen reaches tentative plea deal with federal prosecutors Megathread likely explosive devices addressed to former president obama and former secretary clinton intercepted by law enforcement, linked to device sent to democratic donor george soros Megathread president trump pardons former sheriff joe arpaio A handful of billionaires have spent tens of millions fighting legalization in 2016. wouldn't it be a beautiful \"truck you\" if all 9 states with weed on the ballot voted yes? we have the power to make that happen. votes are more powerful than dollars. links to find your voting precinct inside. vote. For every upvote this thread gets, my arduino will notifiy me with an led text animation /r/altright has been banned. discuss this here. 
<br><br>
Megathread supreme court rejects administration appeal, must continue accepting renewal applications for daca program Let's get niantic's attention people, we need more stuff in rural areas."),
	

	(NULL,"First steps with mySQL ","mysql.jpg","Programming Learn programming I'm alan, and i created imgur. ama. Happy 13th birthday to mysql bug 11472. Here's a sanitized list of 530+ free online programming/cs courses moocs with feedbacki.e. exams/homeworks/assignments that you can start this month december 2016 Let's celebrate. mysql bug 11472 now 10 years old. 
<br><br>
[wtf] first steps with mysql Here's a list of 227 free online programming/cs courses moocs with feedbacki.e. exams/homeworks/assignments that you can start this month june 2016 Here's a list of 221 free online programming/cs courses moocs with feedbacki.e. exams/homeworks/assignments that you can start this month jan 2016 A software engineer hacked a knitting machine to make this stunning star map - sarah spencer, who used a raspberry pi, an arduino compatible board, python and a php/mysql web interface to hack the brother km950i knitting machine. Here's a list of 234 free online programming/cs courses moocs with feedbacki.e. exams/homeworks/assignments that you can start this month july 2016 Udemy coupon 100% off welcome to bootstrap 4 rapid web development framework html css js I’m not a dba. if you want a dba, go hire a dba. Here's a list of 223 free online programming/cs courses moocs with feedbacki.e. exams/homeworks/assignments that you can start this month feb 2016 
<br><br>
Firefox exploit found in the wild which try to steal.bash history,.mysql history,.pgsql history,.ssh configuration files and keys Here's a list of 450+ free online programming/cs courses moocs with feedbacki.e. exams/homeworks/assignments that you can start this month august 2016 Here's a list of 229 free online programming/cs courses moocs with feedbacki.e. exams/homeworks/assignments that you can start this month may 2016 Here's a list of 188 free online programming/cs courses moocs with feedbacki.e. exams/homeworks/assignments that you can start this month feb 2015 I am the oatmeal. ama Here's a list of 241 free online programming/cs courses moocs with feedbacki.e. exams/homeworks/assignments that you can start this month april 2016 119 free udemy coupons, various topics A little somethin' somethin' 
<br><br>
Oracle just laid off 2500 staff from it's solaris and sparc divisions How i taught myself to program; how i would do it again today"),
	

	(NULL,"10 years of Node.js experience","node.png","source plain p add markup stir it up!
Node.js Javascript Company wants 10 years of nodejs experience. nodejs was created 2009. Every 1vn clutch in csgo major history I'm 32 years old, and just started my first full-time job as a developer. one year ago my programming knowledge was basically nil. everything i learned, i found via /r/learnprogramming, so just wanted to share my experience. Github repo with 100+ free resources to learn full stack web development. thank you r/learnprogramming. 
<br><br>
Here's a sanitized list of 530+ free online programming/cs courses moocs with feedbacki.e. exams/homeworks/assignments that you can start this month december 2016 Here's a list of 520+ free online programming/cs courses moocs with feedbacki.e. exams/homeworks/assignments that you can start this month october 2016 Here's a list of 227 free online programming/cs courses moocs with feedbacki.e. exams/homeworks/assignments that you can start this month june 2016 Here's a list of 221 free online programming/cs courses moocs with feedbacki.e. exams/homeworks/assignments that you can start this month jan 2016 Here's a list of 234 free online programming/cs courses moocs with feedbacki.e. exams/homeworks/assignments that you can start this month july 2016 I've completed freecodecamp and received all the certifications. here are few things i want to tell you Here's a list of 155 free online programming/cs courses moocs with feedbacki.e. exams/homeworks/assignments that you can start this month october 2015 Here's a list of 223 free online programming/cs courses moocs with feedbacki.e. exams/homeworks/assignments that you can start this month feb 2016 
<br><br>
Here's a list of 156 free online programming/cs courses moocs with feedbacki.e. exams/homeworks/assignments that you can start this month august 2015 I am john resig, creator of jquery, ama. Here's a list of 450+ free online programming/cs courses moocs with feedbacki.e. exams/homeworks/assignments that you can start this month august 2016 Your guide to monero, and why it has great potential Here's a list of 120 free online programming/cs courses moocs with feedbacki.e. exams/homeworks/assignments that you can start this month jan 2015 Here's a list of 48 free online programming/cs courses moocs with feedbacki.e. exams/homeworks/assignments that you can start this month march 2014 I'm proud to introduce you 4 months of my hard work - hearthbreak.com, the hearthstone demystifier for tournaments, matches, players and videos. [meta] stop dmcas and bandwidth limits. 
<br><br>
 lightning network megathread  Microsoft made a pull request to node.js github repository with an implementation to use chakracore javascript engine as an alternative to v8 engine"),
	

	(NULL,"Angular.js is for serious web developers","angular.png","Angular.js Webdev reddit for web developers Angular momentum Angular momentum This is a demonstration of the conservation of angular momentum using a hoberman sphere, a plastic sphere frame that can be contracted by pulling on a string Doing the maths why the overwatch world is in serious danger 
<br><br>
Conservation of angular mother momentum Angular momentum visualised Angular momentum visualized Hoberman sphere conservation of angular momemntum The frequently circulated image of andromeda as seen if it were brighter depict it at over 8.5 times the average angular diameter of the moon. it is supposed to be only roughly 5.6 times the diameter. i hope we stop circulating this misinformation. Angular momentum Counter-strike global offensive update for 9/15/15 1.35.0.0 New inktober sketch day 16 “angular” thought you guys might like 
<br><br>
Operation angular momentum mk1 was somewhat successful. Angular walls and corners make trees appear inside of this brazilian rainforest home [1000 x 625] Corgi demonstrates the principal of conservation of angular momentum. Moon & saturn angular size comparison. despite being 30 times larger, the ringed planet is so far away that it appears 100 timer smaller than our satellite when viewed from earth. [oc] [2560x2560] The part of the deep web we aren't supposed to see - part 3 - the chase What became of eden Here's a sanitized list of 530+ free online programming/cs courses moocs with feedbacki.e. exams/homeworks/assignments that you can start this month december 2016 My dog and i found a demon in the arizonan desert 
<br><br>
Coming back to frontend after 10 days off Researchers have created a chip for the nano-manipulation of light, paving the way for next gen optical technologies and enabling deeper understanding of black holes.they designed an integrated nanophotonic chip that can achieve unparalleled levels of control over the angular momentum of light."),
	

	(NULL,"Bootstrap 4 released Version 0.16.0","bootstrap.jpg","Webdev reddit for web developers Web design Mrw i've pulled myself up by my bootstraps to become the best person in the world at my job and now regularly engage in private charity to help others do the same so they don't have to rely on the government and wakeup to see that the conservative president has mocked me on twitter But we have to pull ourselves up by the bootstraps right? I am the morninghead guy. in the last year after shark tank, i helped my buddy start a company that's now processing over $350 million/yr. tell us your idea and we'll tell you how to grow it with zero cash like my last ama, we'll answer every single question today. aua. Bootstraps, vital organs, it's all the same. 
<br><br>
Til the phrase \"pull yourself up by your own bootstraps\" was originally meant to describe an absurdly impossible action. the phrase is an adynation, a figure of speech in the form of hyperbole taken to such extreme lengths as to insinuate a complete impossibility. I'm a former us navy seal, staunch libertarian, with an empty bank account, who just made the first campaign contribution of my life to, of all people, a socialist democrat. Homework time. warm up the weaponized autism cannons. Bootstrap 4 released Version 0.16.0 Dear millennials stop complaining and lift yourself by your bootstraps Imagine the sandbox from the perspective of the enemy Til \"pulling yourself up by your bootstraps\" originally meant attempting something ludicrous or impossible 
<br><br>
Here's a list of 227 free online programming/cs courses moocs with feedbacki.e. exams/homeworks/assignments that you can start this month june 2016 Pro tip from dad how to handle sick kids at night. Here's a list of 221 free online programming/cs courses moocs with feedbacki.e. exams/homeworks/assignments that you can start this month jan 2016 [release] unc0ver - the most advanced jailbreak tool \"if you can convince the lowest white man he's better than the best colored man, he won't notice you're picking his pocket. hell, give him somebody to look down on, and he'll empty his pockets for you.\" -lyndon b. johnson Fwd quit complaining about slavery and pull yourself up by your bootstraps. Our idea for a better way to voice chat. Here's a list of 234 free online programming/cs courses moocs with feedbacki.e. exams/homeworks/assignments that you can start this month july 2016 
<br><br>
Bootstrap 4 drops ie9 support and goes full flexbox At age 38 my dad had no savings and started a family. he retired at age 60. hoping this inspires some of the older fire candidates out there that it's possible."),
	

	(NULL,"React is the new Angular","react.png","Javascript Reaction gifs your absurd responses to everything. Vp joe biden reacts to president obama calling him the \"best decision\" he made as a nominee True geordie reacts to logan paul's deleted video. honestly, this is a great watch and perfectly sums up how we all feel about the disgusting prick. Amy schumer tries to \"prank\" kanye west by diving in front of him and pretending to pass out, kanye reacts by walking away Tifu by getting reddit banned in russia 
<br><br>
Families of 44 dead submarine crew react with fury as argentine navy confirms an explosion was recorded last week when it vanished - one widow branded the navy \"perverse bs\" for allowing family members to continue to believe their loved ones could be found alive. Megathread office of special counsel indicts 13 russian nationals and 3 russian entities for interference in 2016 election Megathread f.b.i. raids office of trump’s longtime lawyer michael cohen Megathread fbi director comey fired In august, my psn account was hacked and i found $500 in charges made on my card. sony strings me along for a month, promising a full refund, but ultimately tells me that my only recourse is a chargeback. i issue the chargeback, but sony disputes and inexplicably wins. details inside. Christian parents who 'let their 10-month-old girl die of malnutrition and dehydration after refusing to get help for religious reasons' react in horror as the judge reads out their murder charge Megathread federal court overturns president trump's executive order regarding immigration Megathread michael cohen claims trump knew in advance of 2016 trump tower meeting 
<br><br>
White house chief of staff john kelly reacts as trump goes off script at the un I'm sid fischer, a student who was in the third room shot into by a murderer in the recent school shooting, ama Megathread mueller indicts 12 russians for hacking into dnc Snoop dogg reacts to kanye west's rant at sacramento concert Megathread donald trump jr. releases correspondence from russian lawyer Megathread manafort guilty on eight counts, mistrial declared on 10 more Elon musk reacts to falcon heavy launch Megathread michael flynn resigns as national security advisor 
<br><br>
If you woke up to find you were still 14 years old, and you had just been dreaming of what adult life might be like, how would you react? He reacts to the hand opening"),
	

	(NULL,"SQL Server data warehousing techniques","sql-server.png","Microsoft sql server Programming Which language can i study for 3-5 hours a week and become somewhat proficient in 3 months? My girlfriend is learning some coding for her job. I did not learn any sql today How much sql do you need to know as a developer? 
<br><br>
Codecademy launched learn sql from scratch. I went from excel nerd to a mid-6 figures data warehousing job over the last 6 years. amaa I hit the 100k salary mark. Sql trainer - learn sql queries by doing Learn basics of sql this weekend. live streamed crash course A quick cheatsheet reference for sql queries [do you know] - you can run sql like queries in google sheets for crunching the data - lot of my time is saved today Thanks ea. my password is dynamic and at least 17 characters long for every service i use. there should never be a max password length, there is no reason for it whatsoever. 
<br><br>
Microsoft overtakes amazon as second most valuable u.s. company I just hacked a state election. i’m 17. and i’m not even a very good hacker. How to name your children I just stumbled into the greatest excel tutor of all time Last night, patrick kane became the first player in nhl history to score 2 game-tying goals within the final 200 of regulation. Ififififififififififififif{} Schrödinger's backup the condition of any backup is unknown until a restore is attempted I love what i do i love data science 
<br><br>
3 month job search [oc] So true."),


	(NULL,"Oracle says it is killing the java plugin","oracle.jpg","Dota 2 on reddit For everything about pathfinder. Lpt if ever you need a program you want for free for example a video/photo editor don't search for \"free\", search for \"open source\" to avoid limited trial versions, adverts and malware Oracle cat predicts the winner of the 2018 world cup. In the matrix1999, morpheus nods at the blind man in the lobby of the oracle and he nods back. I had the opportunity to do a photo flight with the blue angels and the oracle bi-plane in san francisco 
<br><br>
Didn’t think oracle was that bad Google wins trial against oracle as jury finds android is “fair use” Jr smith mvp chants in oracle - abc Oracle says it is killing the java plugin The new step by step guide detailing how to get started developing android apps, with no prior experience necessary. includes every resource i used, simple explanations and an interesting first app tutorial. everything you need to get started in android development is here. Jury is picked for $9 billion oracle v. google showdown. only one juror worked with computers, and he was oracle's first strike. Zoe is actually insanely unfun to play against [zach lowe] the night draymond green lost game 7 of the 2016 finals, he sat in the oracle parking lot and made two calls. one was to bob myers to tell him to sign kevin durant. the other was to kevin durant. 
<br><br>
Oracle Rule at my table if you score a crit, you have to come up with a pithy one-liner. I noticed a lot of folks really confused as to just what hyrule warriors is. gather round kids. by the end of this post you'll know if you want it or not. All available dead ghosts + lootable lore triumphs have been found. compilation guide [art oc] i decided to try and recreate an area from oracle of seasons in clay I think i just found out something really big about season 4 or 5. 11 years ago i designed heroes for dota The real reason why we have to keep collecting baryon boughs even though they're useless. 
<br><br>
Google wins trial against oracle as jury finds android is “fair use” Til that when the phrygians were without a king, an oracle at telmessos decreed that the next man to enter the city driving an oxcart should become their king. an unsuspecting peasant farmer named gordias drove into town on an oxcart and was immediately declared king."),
	

	(NULL,"C# is for develpers who don't like C++","csharp.jpg","Learn programming Piano Charlie potraskimy and the transcendentalists- chakra movement in c sharp Pokémon go development archive works in progress, resources, and more. When did musicians start giving easy names to songs? instead of generic names like symphony n.9 x movement, or nocturne no. 20 in c sharp minor Simple sharp line work odin done by c.j. scesa at a stroke of genius in deerfield beac florida 
<br><br>
Antarctica a tabular iceberg can be seen on the right, floating among sea ice just off of the larsen c ice shelf. the iceberg's sharp angles and flat surface indicate that it probably recently calved from the ice shelf, says national aeronautics and space administration nasa on 17 october 2018. Ethereum smart contracts in c - introducing ethsharp Antarctica a tabular iceberg can be seen on the right, floating among sea ice just off of the larsen c ice shelf. the iceberg's sharp angles and flat surface indicate that it probably recently calved from the ice shelf, says national aeronautics and space administration nasa on 17 october 2018. Corvettes mid engine concept car at aliso viejos c and c. sharp looking car, and love the silver grey matte finish. Chopin played on authentic period instruments. if you love chopin, you'll love this post. C sharp I just released csharpsharp, the missing libraries of c. it's open-source. Tifu when my wife insisted that d-flat is the same as c-sharp. 
<br><br>
Please let me introduce to you my own music generating software the platonic music engine. i'm a composer and not a programmer so i tried to create this software from that perspective. No penalty for torture on thursday,[ag] eric holder jr. announced that no one would be prosecuted for the brutal deaths of two prisoners held in c.i.a. custody.[putting] into sharp and shameful focus the obama administration’s overall record of trying to avoid legal scrutiny of bush-era abuses. antarctica a tabular iceberg can be seen on the right, floating among sea ice just off of the larsen c ice shelf. the iceberg's sharp angles and flat surface indicate that it probably recently calved from the ice shelf, says national aeronautics and space administration nasa on 17 oct 2018. Idea on how to film dan simmons's hyperion Xamarin is working on websharp, c on the web browser What are the most rock and roll sounding classical pieces? Ethereum smart contracts in c - introducing ethsharp An e, f sharp, g, a, b, c, d, and another e walk into a bar. 
<br><br>
Eli5 why some musical notes do not have a sharp/flat in between them like e and f or b and c I learned last week that charlie parkers' popular intro to the standard all the things you are was a parody of rachmaninov's piano prelude in c sharp minor."),


	(NULL,"Get on route with Ruby on Rails","ruby.jpg","Ruby programming and resources for information security Ruby on rails Ruby may Ruby may ruby mayyy Ruby may ruby mayyy Ruby may ruby mayyy 
<br><br>
Ruby may Apparently is ruby the only viable solo q hero in the game. 12 games and counting. Ruby bhogal from the newest series of great british bake off is unbelievably beautiful Ruby rose, but she’s just fucking done with everything part 3 [cslucaris] Ruby rose named most dangerous celebrity to search online Official first discussion thread—volume 6, chapter 1 the argus limited Awesome ruby rhod costume Grimmed rose dishwasher1910 
<br><br>
Volume 6 trailer. Steve the mad lad with naming conventions The great british bake off week ten the grand final. Shoutout to this guy for always believing in me Birthday girl dishwasher1910 Schnee’s daddy pockynuko12000 How things have changed [milkpuppy77] Proposal observe this image by catwithabrush 
<br><br>
Rwby volume 6 sneak peek who needs bodyguards? ign Giveqrowabreak2k18"),


	(NULL,"JavaScript jokes so bad you have to facepalm","javascript.gif","Webdev reddit for web developers Coding Are you aware? comcast is injecting 400+ lines of javascript into web pages. Old meme format, timeless javascript quirks I'd rather javascript Well, javascript 
<br><br>
We build internet explorer. i know, right? ask us just about anything. Til there's a community called \"dwitter\" where people compose 140 character javascript programs that produce interesting visuals Javascript dreams A wizard appears and offers you mastery in a skill of your choice. you will be given 10 years worth of practice and experience for that skill in an instant. which skill would you choose? Lpt how to get the most out of google/search enginesboolean searches & additional tricks - long post, but have always found it very useful for general & specific searches Javascript is getting real tired of your jokes After 6 months of warning users, we finally did it. tonight, i denied 2,400 windows 7 computers from log on. You learn every day, with javascript. 
<br><br>
Something something javascript I can not recommend freecodecamp more. how the hell is that free? The one true javascript exception handler Lpt block websites from forcing you to disable your ad block by turning off javascript for them in the chrome settings menu. [[][[]]+[]][+[]][++[+[]][+[]]] is \"n\" in javascript And now a word from reddit’s engineers… Interactive replay of the premier league 15/16 with gifs Javascript injection attack in japan supermarket 
<br><br>
How only relying on javascript for html form input validation is like Javascript jokes so bad you have to facepalm."),
	

	(NULL,"Microsoft tech giant hiring 2000 new developers","microsoft.jpg","Sysadmin Windows 10 [x-post] remember my xbox one ad concept? microsoft just copied it. Remember my xbox one ad concept? microsoft just copied it. Susan kare, famous apple artist who designed many of the fonts, icons, and images for apple, next, microsoft, and ibm. 1980s \"endgame\", microsoft paint [1978x1316] [oc] 
<br><br>
Til a harvard professor who had worked with bill gates called him shortly after he had left to start microsoft. the professor recalled, \"he had moved to albuquerque. to run a small company writing code for microprocessors, of all things. i remember thinking 'such a brilliant kid. what a waste.'\" Til in 2010, microsoft banned a user from xbox live for putting fort gay as his address. when he tried to tell them that fort gay actually exists in west virginia, it took an appeal from the town’s mayor for it to be corrected. My girlfriends dad was a microsoft employee that was part of the launch team in 2001. he told me i could have what ever was left in his old house. so i grabbed this. Microsoft's next console name Til when steve jobs accused microsoft of stealing idea for windows from mac, bill gates replied \"well, steve,. i think it's more like we both had this rich neighbor named xerox and i broke into his house to steal the tv set and found out that you had already stolen it.\" Microsoft co-founder paul allen dies of cancer at age 65 The cloud act would let cops get our data directly from big tech companies like facebook without needing a warrant. congress just snuck it into the must-pass omnibus package. Microsoft are definitely to blame for this. 
<br><br>
8 months ago microsoft and sony both said they were open to cross platform play. let's keep the conversation active so devs see we are interested in it. Microsoft paint magic. Hey, microsoft, stop installing third-party apps on clean windows 10 installs. Lpt if ever you need a program you want for free for example a video/photo editor don't search for \"free\", search for \"open source\" to avoid limited trial versions, adverts and malware Microsoft paint forever, jim’ll paint it, ms paint, 2017 I live in the central african bush. we pay for slow satellite internet per mb d/l. just one of our computers has secretly d/l'ed 6gb for windows 10. we track & coordinate anti-poaching rangers in the field with these pc's + gps. f you microsoft. Microsoft paint to be killed off after 32 years | technology This ad for the new microsoft surface studio looks like it was taken in 1982 
<br><br>
Microsoft's 'teen girl' ai, tay, turns into a hitler-loving sex robot within 24 hours Local bakery had no picture for the apple turnover, so they decided a microsoft paint version would do instead."),
	

	(NULL,"Windows 8 is the worst move since \"La Macarena\"","windows8.jpg","R/windowsphone Techsupport Windows 10 ltsc 2019 x64 en iso Updating a cracked version of windows 10 Is it safe to use pirated windows ? How to download and install windows 10 ltsb 
<br><br>
If your computer is using around 40-50% ram while idle, windows tips and tricks might be the cause. Msguides windows 10 activation Get digital license for free on any currently available windows 10 editions. Windows loader v2.2.2 download What is going in with windows 10 ltsc? Hey, microsoft, stop installing third-party apps on clean windows 10 installs. This shop has mirrored its sign to take advantage of the popular christmas window display in the shop opposite. My husband built this inside playhouse for our foster children. it has a kitchen and real working windows and lights. 
<br><br>
I'm not allowed a dog, so my neighbors built a window into my yard so i can pet theirs. New benchmark shows new ipad pro does indeed smoke windows i7 core laptops The frosting on my car window was melted by the sun through the mirror. Eight years ago, i visited france and went on a tour of castles in the loire valley. this dog was hanging out the window staring longingly. everyone left the tour to give him pets. 10/10 good castle boy. Raging flood smashes in a storefront’s windows and floods the place as staff tries to hold the doors closed. Spraying the train with opened windows \"those who cannot see out their rear view window are doomed to repeat it.\" Windows 10’s next release will let you uninstall more built-in apps 
<br><br>
Canola field in idaho looks just like the iconic windows wallpaper. This sunset looked split in half through my two windows"),


	(NULL,"Why I really miss my MacBook Pro","macbook.jpg","Applehelp Pc master race - spearheading the second golden age of pc gaming Apple used ice to seize louis rossmann's shipment of original macbook batteries [super awesome update] sat down on my friend's macbook and broke it, offered to pay her the money for it but now she wants more because \"she was upgrading anyway\" so it's this or she will sue me in small claims court. I just won a macbook air for $1.00 Tifu by almost murdering my friend and stopping a school-wide arms race. 
<br><br>
Apple's holier-than-thou attitude is their undoing in court Apple is suing a man that teaches people to repair their macbooks [original working link] Apple fans are returning their new macbook pros that cost a minimum of $2,800 because they can't reach the advertised speeds Apple's newest macbook pro is the first macbook not recommended by consumer reports Apple fans are returning their new macbook pros that cost a minimum of $2,800 because they can't reach the advertised speeds Apple's new proprietary software locks kill independent repair on new macbook pros - failure to run apple's proprietary diagnostic software after a repair \"will result in an inoperative system and an incomplete repair.\" To those saying the new macbook touchbar is useless Til that a high school in pennsylvania issued a macbook to each of its 2,306 students, then remotely activated the webcams to spy on the students at home. 
<br><br>
Til that the microcontroller inside a macbook charger is about as powerful as the original macintosh computer. Apple's new macbook disconnects microphone \"physically\" when lid is closed After the macbook launch event, apple now sells 17 different types of dongle Apple finally acknowledges faulty macbook keyboards with new repair program Is the macbook pro the future of laptops? Apple says new macbook pro has only 16gb of ram to save battery life Consumer reports stands by its verdict, won't recommend apple's macbook pro Apple on the new macbook pro 
<br><br>
In unthinkable 2010 the second last bomb is being defused with microsoft excel on a macbook Apple confirms macbook pro thermal throttling, software fix coming today"),
	

	(NULL,"Semicolon hell!","semicolon.gif","Grammar Programmer humor When you use a semicolon on your exam What happened when the semicolon broke grammar laws? Years ago, my pokémon stopped me from suicide. today, i joined the semicolon project by showing that. What i think whenever i see another semicolon post 
<br><br>
What you need to know before you start steins;gate 0 Lpt as a science/math major, this is how i improved my college essays using 5 formulas. Semicolons Santa and mrs. claus have decided to break up Semicolons Til that kurt vonnegut has said that the only reason to use a semicolon is \"to show you've been to college.\" If you see someone with a semicolon on their body, here’s what it really means I grade a student's homework very loosely, he wanted it graded strictly 
<br><br>
The semicolon is probably now used more often in winky faces than its actual grammatical purpose. There are no divorce courts at the north pole, That's not an airgap either. More people know how to correctly use a semicolon in an emotion than in a sentence. I made a mod for freely setting your first-person field of view. Just what i needed. an advanced semicolon. I'd map it as a semicolon x-post r/interestingasfuck If a person's colon is cut in half, does it become a semicolon? 
<br><br>
This is what a semicolon looks like in russian If i get too excited while on my period, does it turn into an exclamation point?"),


	(NULL,"Why a Software Developer is not a Software Engineer","engineer.jpg","Software development - methodologies, techniques, and tools. covering agile, rup, waterfall + more. Cs career questions What free software is so good you can't believe it's free? R/softwaregore What free software is so good you can't believe it's available for free? Sites with 100% verified / virus-free software? 
<br><br>
[software][crack] youtubetoclick installer + crack dll. Faq call 5 \"what screenwriting software should i use\" [give us the best response to the question in the comments][upvote the best answer - it’ll then be used in the revamped faq] Cracked office works just like the real thing, from r/iamverysmart [software] all adobe applications [windows][mac] - 2018 update What software should everyone have installed on their computer? Not being accepted in major wanted It's official ibm is acquiring software company red hat for $34 billion Youtube | nintendo switch download software | games 
<br><br>
Til in 2005, a guy named doug heckman read the eula before he installed some pc software. the agreement included a clause offering 'financial compensation' to licensees who actually read the license agreement. he emailed the company, referred to the clause and the company sent him a check for $1,000 Plugging 50,000 portraits into facial recognition/emulation software can generate some pretty fascinating nightmare fuel. Apple's new proprietary software locks kill independent repair on new macbook pros - failure to run apple's proprietary diagnostic software after a repair \"will result in an inoperative system and an incomplete repair.\" Chinese authorities have begun deploying a new surveillance tool called \"gait recognition\" software that uses people's body shapes and how they walk to identify them, even when their faces are hidden from cameras. Amazon employees protesting sale of facial recognition software Google's new phone software aims to end telemarketer calls for good Apple's new macbook disconnects microphone \"physically\" when lid is closed Ibm nears deal to acquire software maker red hat 
<br><br>
Why it people should never take an adult learning software class at the local community college Apple is using proprietary software to lock macbook pros and imac pros from third-party repairs"),
	

	(NULL,"Apache server updates for 2018","apache.png","Apache spark Apache kafka Megathread 2 michael flynn testifies in plea that he was directed to make contact with russia by senior trump transition team officials Megathread trump informs aides of decision to remove steve bannon from white house staff Apache pilots marry at west point Ma'am for the 50th time we cannot give you your sons password. 
<br><br>
In 1973, marlon brando sent an apache woman to the oscars to refuse his award for him on the basis of how the film industry treats native americans. The ah-64 apache's gun-to-helmet tracking system My apache father and my english mother on a date in 1979 Apache helicopter showing off Greatly improve fps, new method. Those four delicious words An apache backward leap with flare countermeasure Reloading the 30mm chain gun on an apache helicopter 
<br><br>
Marlon brando never accepted his award for his performance for the godfather, but rather had an apache native american talk about indian rights and was subsequently boo'ed. Apache chief geronimo, ca. 1900. Having fun in $35m apache helicopter Cannon follows pilot’s head movement - ah - 64 apache It's all coming together. clinton, the middle east, north africa, big pharma, the international center for missing & exploited children Hattie tom, a very beautiful chiricahua apache - 1899 Megathread democrats block gorsuch consideration Apache attack helicopter 
<br><br>
Hey, i went through officers training. learned to fly apache helicopters. made it through sere school. flew missions in combat zones. but hey, my opponent has made a living through a deep state career. pretty easy choice michipedes. Apache fireball - 1949 vintage air rifle refurbishment"),


	(NULL,"IBM's newest supercomputer rocks the boat","ibm.jpg","Non-ibm controlled subreddit R/mechanicalkeyboards for all the click and none of the clack. Susan kare, famous apple artist who designed many of the fonts, icons, and images for apple, next, microsoft, and ibm. 1980s Ibm ball head typewriter 5mb ibm hard drive 1956 Ibm's watson was tested on 1,000 cancer diagnoses made by human experts. in 30 percent of the cases, watson found a treatment option the human doctors missed. some treatments were based on research papers that the doctors had not read. more than 160,000 cancer research papers are published a year. 
<br><br>
No one wants to help donald trump build a registry of muslims tech giants microsoft and ibm have said they would refuse to help create a registry of muslim americans under trump's presidency It's official ibm is acquiring software company red hat for $34 billion This is an actual picture of a molecule, taken by ibm. Ibm watson has identified therapies for 323 cancer patients that went overlooked by a molecular tumor board. researchers said next-generation genomic sequencing is \"evolving too rapidly to rely solely on human curation\" when it comes to targeting treatments. I've probably taken this retro sleeper pc build thing a bit too far. 1995 ibm aptiva, custom fab, welding, crt, htc vive vr, sd card floppy diskette, and upgraded internals. yes, that really is windows 10 turned into windows 95. i still have loads more to do. Ibm's optical storage is 50 times faster than flash and is now cheaper than ram. Ibm has a website where you can write experiments that will run on an actual quantum computer. In a new world record, scientists at ibm have captured 330 terabytes of uncompressed data — or the equivalent of 330 million books — into a cartridge that can fit into the palm of your hand. 
<br><br>
Megathread president trump ends c.e.o. advisory councils Under pressure, western tech firms bow to russian demands to share cyber secrets - companies, including cisco, ibm & sap, are acceding to moscow's demands for access to closely guarded product security secrets, at a time when russia is accused of a growing number of cyber attacks on the west Ibm makes breakthrough in race to commercialize quantum computers - in the experiments described in the journal nature, ibm researchers used a quantum computer to derive the lowest energy state of a molecule of beryllium hydride, the largest molecule ever simulated on a quantum computer. Til in 1994, ibm released a cell phone with touch screen and e-mail. it could also send and receive faxes, work as a pager, and was considered the world's first smart phone due to its features and capabilities. Til that to prepare ibm's watson for jeopardy, researchers inputted the entirety of urban dictionary. unfortunately, this had the side effect of watson adopting profanity. in one test, it even used the word \"bullshit\" to respond to a researcher's query. Til ibm had to delete 'urban dictionary' data from the watson super computer system because the machine started cursing. So i sold a reddit reply to warner brothers a few years back my first novel acadia comes out today. ama. Canada's homegrown tech firms say they've been shut out of a multimillion-dollar project to consolidate the federal government's data operations, with american giants such as ibm and microsoft getting the inside track. 
<br><br>
5 mb harddrive being shipped by ibm - 1956. Ai and chinese doctors “at least 40 hospitals in china have deployed ibm’s watson. beijing-based huiyihuiying, for instance, said it has ai doctors capable of interpreting ct scans. reading a ct scan and making diagnoses within seconds compared to five minutes needed by human doctors.”"),


	(NULL,"As hardware shrinks it gets harder to repair","hardware.jpg","Hardwareswap Pc master race - spearheading the second golden age of pc gaming Critical space flight hardware \"do not touch\" Co-worker went on vacation, so we \"upgraded\" his hardware. he reddits so here's to him finding out before he gets back. On my way to return comcast’s shitty hardware and stumble across this hero. The importance of a fire door and the appropriate hardware. 
<br><br>
Pinterest needs to be removed from google imo My grandpa uses the actual hardware for labeling the drawers My local hardware has a dog that follows you around, and takes your items to the counter for you. My local hardware store has a pet turtle that wanders the store early in the am Hardware store taking care of our fellow wildlife. Warning do not skin your nintendo switch. High prices of hardware Penguins are just seal software running on bird hardware. 
<br><br>
We are linus tech tips, a youtube channel that employs 20 people - ask us anything. Lpt modems are the biggest racket in the cable business. don't opt for theirs, you pay $12/month for life, as apposed to the one time cost of $30 - $100. only set up required is giving the isp the mac address on the box, and you dont have to wait for the installer to come \"between 8am and 2pm\" We are linus tech tips, makers of youtube tech videos - ask us anything. Some assembly required. good luck. This mushroom growing out of a bag of mulch at our local hardware store. When disassembling items, punch your screws thru some cardboard and label the sets. this will help you retain your hardware, remember placement and order of reassembly Dead or alive xtreme pc will downgrade boob physics on low-end hardware Hardware and tear 
<br><br>
What's the difference between usa and usb? Foxes are just cat software running on dog hardware"),


	(NULL,"Jump start your career with Java","java.png","Programming Learn java Lpt if ever you need a program you want for free for example a video/photo editor don't search for \"free\", search for \"open source\" to avoid limited trial versions, adverts and malware Are you aware? comcast is injecting 400+ lines of javascript into web pages. Old meme format, timeless javascript quirks I'd rather javascript 
<br><br>
We build internet explorer. i know, right? ask us just about anything. Surfing in java, indonesia Til there's a community called \"dwitter\" where people compose 140 character javascript programs that produce interesting visuals Skyrim is the new java Distribution of digits generated by java's random number function [oc] Java heatmap Oracle says it is killing the java plugin The new step by step guide detailing how to get started developing android apps, with no prior experience necessary. includes every resource i used, simple explanations and an interesting first app tutorial. everything you need to get started in android development is here. 
<br><br>
Java irl Years ago i wrote a java application which \"draws\" dna sequences. here is a compilation of some common viruses put next to each other [oc] I made a free youtube player for electronic music. each day i load it with 12,000 videos that correspond to tracks which djs have downloaded the most during the previous 31 days from beatport, juno and traxsource you stream what djs are buying info in comments - feedback welcome A wizard appears and offers you mastery in a skill of your choice. you will be given 10 years worth of practice and experience for that skill in an instant. which skill would you choose? C programmers when they meet a java dev Java, pixel art, 2018. Lpt how to get the most out of google/search enginesboolean searches & additional tricks - long post, but have always found it very useful for general & specific searches Mount bromo, east java, indonesia [oc] 2820x1600 
<br><br>
Riot heading in right direction with graves' cigar Darn java")
;