<?php include 'includes/config.php'?>
<?php get_header()?>
<?php

// Create connection
$conn = new mysqli(DB_SERVER, DB_USER, DB_PASSWORD, DB_NAME);
// Check connection
if ($conn->connect_error) {
    //die("Connection failed: " . $conn->connect_error);
}

$sql = "select * from blogs";
$result = $conn->query($sql);

if ($result->num_rows > 0) {
    // output data of each row
    while($row = $result->fetch_assoc()) {
       /* echo '
          <div class="post-preview">
            <a href="blog.php?id=' . $row['BlogID'] . '">
              <h2 class="post-title">' .
                $row['BlogTitle']
              . '</h2>
            </a>
            <p class="post-meta">Posted by' .
              
              substr($row['BlogEntry'], 0, 140)
              .
            '</p>
          </div>
          <hr>
        ';*/

echo '
        <p><b>BlogID: </b>' . $row['BlogID'] . '<br>
        <b>BlogTitle: </b>' . $row['BlogTitle'] . '<br>
        <b>BlogImg: </b>' . $row['BlogImg'] . '<br>
        <b>BlogEntry: </b>' . substr($row['BlogEntry'], 0, 50) . '</p>
        <hr>
      ';


    }
} else {
    echo "<p>No blog entries found.</p>";
}
$conn->close();

echo '
  <p>Disclaimer: fake blog entries generated by: http://lipsum.ahyeah.nl/#</p>
';

/*
  $result = get_all_blogs();  
  
  if(mysqli_num_rows($result) != 0) {
    while($row = mysqli_fetch_assoc($result)) {
      echo '
        <p><b>BlogID: </b>' . $row['BlogID'] . '<br>
        <b>BlogTitle: </b>' . $row['BlogTitle'] . '<br>
        <b>BlogImg: </b>' . $row['BlogImg'] . '<br>
        <b>BlogEntry: </b>' . substr($row['BlogEntry'], 0, 50) . '</p>
        <hr>
      ';
    }
  }else{
    echo '
      <p>Error in sql table.  Reload the sql script to reload the test data</p>
    ';
  }

  mysqli_free_result($result);
*/
?>
<?php get_footer()?>